# -*- coding: utf-8 -*-
"""20220204039_Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0KYTOwKS2GL2woXuyetF7cZ1_IgHxBn

# **Student ID: 20220204039**


# Assignment 2: Audio Steganography Lab Assignment

### Course: CSE 4174 | Cyber Security Lab

### Department: Computer Science & Engineering

### Ahsanullah University of Science and Technology
"""

!pip install pydub
!apt-get install -y ffmpeg

# Task 1: RECORD YOUR NAME & CONVERT TO .WAV

import wave
import struct
import os
import numpy as np
from datetime import datetime
from google.colab import files
from pydub import AudioSegment


print("TASK 1: Record Your Name & Convert to WAV")
print("=" * 60)

# Upload your recorded audio file
print("\n Please upload your recorded audio file (.m4a, .mp3, or other format)")
uploaded = files.upload()

# Get the uploaded filename
filename = list(uploaded.keys())[0]
print(f"\nUploaded file: {filename}")

# Convert to .wav
audio = AudioSegment.from_file(filename)
audio.export("my_recording.wav", format="wav")
print("\n Converted successfully! File saved as my_recording.wav")

# Verify the WAV file was created
if os.path.exists("my_recording.wav"):
    print(" my_recording.wav is ready for use!")
else:
    print(" Conversion failed. Please try again.")

# Task 2: Hide Your Student ID in the Audio File (Encoding Using LSB)

print("TASK 2: Hide Your Student ID")
print("=" * 60)

def encode_audio(input_file, output_file, secret_message):
    # Open the WAV file
    with wave.open(input_file, 'rb') as wav_in:
        # Get audio parameters
        n_channels = wav_in.getnchannels()
        sample_width = wav_in.getsampwidth()
        framerate = wav_in.getframerate()
        n_frames = wav_in.getnframes()

        # Read all frames
        frames = wav_in.readframes(n_frames)

    # Convert frames to list of integers (samples)
    # Using struct to unpack the binary data
    if sample_width == 1:  # 8-bit audio (unsigned)
        samples = list(struct.unpack(f'{n_frames * n_channels}B', frames))
    elif sample_width == 2:  # 16-bit audio (signed)
        samples = list(struct.unpack(f'{n_frames * n_channels}h', frames))
    else:
        raise ValueError(f"Unsupported sample width: {sample_width}")

# Prepare the secret message (Convert secret message + delimiter to binary)

    # Add delimiter to mark end of message
    secret_message_with_delimiter = secret_message + "####"

    # Convert message to binary string
    binary_message = ''.join(format(ord(char), '08b') for char in secret_message_with_delimiter)

    # Check if audio has enough capacity for the message
    if len(binary_message) > len(samples):
        raise ValueError(f"Message too long! Need {len(binary_message)} bits but only {len(samples)} available.")

    # Embed the message bit by bit into the LSB of each sample
    encoded_samples = samples.copy()

    for i, bit in enumerate(binary_message):
        # Clear the LSB and set it to the message bit
        encoded_samples[i] = (encoded_samples[i] & ~1) | int(bit)

    # Convert back to binary data
    if sample_width == 1:
        encoded_data = struct.pack(f'{len(encoded_samples)}B', *encoded_samples)
    elif sample_width == 2:
        encoded_data = struct.pack(f'{len(encoded_samples)}h', *encoded_samples)
    else:
        raise ValueError(f"Unsupported sample width: {sample_width}")

    # Write the encoded audio to a new WAV file
    with wave.open(output_file, 'wb') as wav_out:
        wav_out.setnchannels(n_channels)
        wav_out.setsampwidth(sample_width)
        wav_out.setframerate(framerate)
        wav_out.writeframes(encoded_data)

    print(f"\n Message encoded and saved to {output_file}")
    print(f"   - Message: '{secret_message}'")
    print(f"   - Message length: {len(secret_message)} characters")
    print(f"   - Bits embedded: {len(binary_message)} bits")
    print(f"   - Audio capacity: {len(samples)} bits")
    print(f"   - Used: {(len(binary_message) / len(samples) * 100):.2f}% of capacity")

# Enter your student ID (last 3 digits)
print("\nEnter your student ID (last 3 digits):")
student_id_last3 = input("Enter last 3 digits of your student ID: ")

# Validate input
if len(student_id_last3) != 3 or not student_id_last3.isdigit():
    print("\n Invalid input! Please enter exactly 3 digits.")

print(f"\nHiding your student ID: {student_id_last3}")

# Encode the student ID into the audio file
try:
    encode_audio("my_recording.wav", "encoded_audio.wav", student_id_last3)
    print("\n Task 2 Complete: Student ID hidden in encoded_audio.wav")
except Exception as e:
    print(f"\n Error during encoding: {e}")

# Task 3: Extract the Hidden ID

print("TASK 3: Extract the Hidden ID")
print("=" * 60)

def decode_audio(encoded_file):

    # Open the encoded WAV file
    with wave.open(encoded_file, 'rb') as wav_in:
        n_channels = wav_in.getnchannels()
        sample_width = wav_in.getsampwidth()
        n_frames = wav_in.getnframes()
        frames = wav_in.readframes(n_frames)

    # Convert frames to list of integers (samples)
    if sample_width == 1:  # 8-bit audio (unsigned)
        samples = list(struct.unpack(f'{n_frames * n_channels}B', frames))
    elif sample_width == 2:  # 16-bit audio (signed)
        samples = list(struct.unpack(f'{n_frames * n_channels}h', frames))
    else:
        raise ValueError(f"Unsupported sample width: {sample_width}")

    # Extract the LSB from each sample and reconstruct the binary message
    bits = []
    for sample in samples:
        bits.append(str(sample & 1))

    # Convert bits back to characters (8 bits per character)
    binary_string = ''.join(bits)
    chars = []
    for i in range(0, len(binary_string), 8):
        byte = binary_string[i:i+8]
        if len(byte) < 8:
            break
        char = chr(int(byte, 2))
        chars.append(char)
        # Stop if we find the delimiter
        if ''.join(chars).endswith("####"):
            break

    decoded_message = ''.join(chars)

    # Remove the delimiter
    if "####" in decoded_message:
        decoded_message = decoded_message.split("####")[0]

    return decoded_message

# Decode the hidden message
try:
    extracted_id = decode_audio("encoded_audio.wav")
    print(f"\n Extracted hidden ID: {extracted_id}")
    print(f"   - Extracted message length: {len(extracted_id)} characters")

    # Verify the extracted ID matches what was hidden
    if extracted_id == student_id_last3:
        print("Verification: MATCHES the original student ID!")
    else:
        print(f"Verification: Extracted '{extracted_id}' vs Original '{student_id_last3}'")

except Exception as e:
    print(f"\n Error during decoding: {e}")
    print("   Make sure encoded_audio.wav exists and was properly encoded.")